title: "Dr. Staffan Canback"
description: "Bridging Science and Management"
logo: "/assets/images/logo-canback-think-v.svg"

url: "https://canback.net"
baseurl: "/docs"



remote_theme: pages-themes/slate@v0.2.0

author:
  name: "Staffan Canback"
  url: "https://canback.net/docs/about/"
  type: Person

social:
  name: "Staffan Canback"
  links:
    - "https://www.linkedin.com/in/scanback/"
    - "https://www.threads.com/@canback_think"
    - "https://medium.com/@scanback"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

sitemap:
  path: /docs/sitemap.xml

