title: "Dr. Staffan Canback"
description: "Bridging Science and Management"
logo: "/assets/images/logo-canback-think-v.svg"

url: "https://canback.net"
baseurl: "/docs"



remote_theme: pages-themes/slate@v0.2.0

author:
  name: "Staffan Canback"
  url: "https://canback.net/docs/about/"
  type: Person

social:
  name: "Staffan Canback"
  links:
    - "https://www.linkedin.com/in/scanback/"
    - "https://www.threads.com/@canback_think"
    - "https://medium.com/@scanback"
    - "https://orcid.org/0009-0006-9892-398X"
    - "https://figshare.com/authors/Staffan_Canback/20547296"
    - "https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=370890"
    - "https://ideas.repec.org/e/pca59.html"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

sitemap:
  path: /docs/sitemap.xml

